name: Distribution cleanup

on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  actions: none
  checks: write
  id-token: none

jobs:
  cleanup-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cleanup old dist files
        run: |
          cd dist
          for tag in $(git tag --sort=-creatordate); do
              files=( *${tag}* )
              if [ ${#files[@]} -gt 1 ]; then
                  # keep newest, delete older
                  newest="${files[-1]}"
                  for f in "${files[@]}"; do
                      if [ "$f" != "$newest" ]; then
                          rm "$f"
                      fi
                  done
              fi
          done
          cd ..

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Commit and push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          # Always sync with remote first
          git fetch origin master
          git reset --hard origin/master

          # Stage and commit if there are changes
          git add dist
          if ! git diff --quiet --cached; then
            git commit -m "[Auto-commit] Distribution cleanup [skip ci]"
          fi

          # Push with retries, but fail if never succeeds
          RETRIES=10
          for i in $(seq 1 $RETRIES); do
            if git push https://x-access-token:$PAT_TOKEN@github.com/${{ github.repository }} HEAD:master; then
              echo "Successfully pushed changes."
              exit 0
            else
              echo "Push failed, retrying ($i/$RETRIES)..."
              sleep 3
            fi
          done

          echo "Push failed after $RETRIES attempts."
          exit 1
