name: Distribution cleanup

on:
  push:
    tags:
      - '*'

jobs:
  cleanup-dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cleanup old dist files
        run: |
          cd dist
          for tag in $(git tag --sort=-creatordate); do
              files=( *${tag}* )
              if [ ${#files[@]} -gt 1 ]; then
                  # keep newest, delete older
                  newest="${files[-1]}"
                  for f in "${files[@]}"; do
                      if [ "$f" != "$newest" ]; then
                          rm "$f"
                      fi
                  done
              fi
          done
          cd ..

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Commit and push scraped data
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git add dist
          git diff --quiet && git diff --staged --quiet || git commit -m "[Auto-commit] Distribution cleanup [skip ci]"
          
          RETRIES=10
          for i in $(seq 1 $RETRIES); do
            git pull --rebase
            git push https://x-access-token:$PAT_TOKEN@github.com/${{ github.repository }} HEAD:master && break || {
              echo "Push failed, retrying ($i/$RETRIES)..."
              sleep 3
            }
          done
