name: Unit tests

on:
  push:
  pull_request_target:  # for safety: only run on base repo, not forked ones
  workflow_dispatch:
  
permissions:
  contents: read
  actions: none
  checks: write
  id-token: none

jobs:
  test:
    runs-on: imggenhub-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry (cross-platform)
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
              # Download and install Poetry via PowerShell
              powershell -Command "
                Invoke-WebRequest -Uri 'https://install.python-poetry.org' -UseBasicParsing -OutFile 'install-poetry.py';
                py install-poetry.py --version 1.8.2
              "
              export PATH="$USERPROFILE\AppData\Roaming\Python\Scripts:$PATH"
          else
              # Linux/macOS
              curl -sSL https://install.python-poetry.org | python3 - --version 1.8.2
          fi
          poetry --version

      - name: Install Poetry (Ubuntu)
        if: runner.os != 'Windows'
        uses: snok/install-poetry@v1
        with:
          version: 1.8.2

      - name: Install dependencies
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
              export PATH="$USERPROFILE\AppData\Roaming\Python\Scripts:$PATH"
          fi
          poetry install --no-interaction
        shell: bash

      - name: Run unit tests
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
              export PATH="$USERPROFILE\AppData\Roaming\Python\Scripts:$PATH"
          fi
          poetry run python -m unittest discover -s tests
        shell: bash

      - name: Upload coverage to Codecov
        if: success()
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
        continue-on-error: true
